kind: ConfigMap
apiVersion: v1
metadata:
  name: common-config
data:
  application.yml: |-
    logging:
      level:
        org.springframework.security: INFO

    security:
      oauth2:
        resource:
          jwt:
            keyValue: ${JWT_KEY}
