apiVersion: v1
kind: Secret
metadata:
  name: oauth2-secret
type: Opaque
data:
  secret_key: TlRaTW9Od2l3N2ZpbDR2dnlnZHRRRHBqNVBVeGU5eWNxdU9DNkYySnJyaWJqczdjcnFMaTlkNkkyWVM3VHFrNTB2MHl5enh5RmVYa216OTJxa0FoNlBsTW1INEFObUpyMXNK