apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  client-browser-password: e25vb3B9
  client-menu-service-password: e25vb3B9cGFzc3dvcmQ=
  client-order-service-password: e25vb3B9cGFzc3dvcmQ=