app:
  jwt:
    singning:
      key: NTZMoNwiw7fil4vvygdtQDpj5PUxe9ycquOC6F2Jrribjs7crqLi9d6I2YS7Tqk50v0yyzxyFeXkmz92qkAh6PlMmH4ANmJr1sJ

  clients:
    browser:
      name: 'browser'
      password: '{noop}'
      scope: ui
    menu:
      name: 'menu-service'
      password: '{noop}password'
      scope: server
    order:
      name: 'order-service'
      password: '{noop}password'
      scope: server
