eureka:
  client:
    registerWithEureka: false

# Solution of the following issue:
# - The Hystrix timeout of 20000ms for the command menu-service is set lower
#   than the combination of the Ribbon read and connect timeout, 80000ms.
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*' # ignores service mapping
  routes:
    auth:
      path: /uaa/**
      serviceId: auth-service
      sensitiveHeaders:
    menu:
      path: /menubook/**
      serviceId: menu-service
      sensitiveHeaders: