apiVersion: v1
kind: Service
metadata:
  name: menu-service
  labels:
    app: menu-service
spec:
  type: NodePort
  selector:
    app: menu-service
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30084